// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package PharmaGest;

/************************************************************/
/**
 * 
 */
public class Clients {
	
	public String carteVitale;
	/**
	 * 
	 */
	String nom;
	/**
	 * 
	 */
	String prenom;
	/**
	 * 
	 */
	public int age;
	/**
	 * 
	 */
	public int poids;
	/**
	 * 
	 */
	public int taille;
	/**
	 * 
	 */
	String adresse;
	/**
	 * 
	 */
	int tel;
	/**
	 * 
	 */
	public Prescription prescription;
	/**
	 * 
	 */
}
