// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package PharmaGest;
import java.util.*;

/************************************************************/
/**
 * 
 */
public class Commande {
	/**
	 * 
	 */
	String num;
	/**
	 * 
	 */
	public Date date;
	/**
	 * 
	 */
	public Fournisseurs fournisseurs;
}
