// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package PharmaGest;
import java.util.*;

/************************************************************/
/**
 * 
 */
public class Facture {
	/**
	 * 
	 */
	public String code;
	/**
	 * 
	 */
	public Date date;
	/**
	 * 
	 */
	String num;
	/**
	 * 
	 */
	public Livraison livraison;
}
