// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package PharmaGest;
import javafx.event.ActionEvent;
import javafx.scene.control.Button;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TextField;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import javafx.fxml.FXML;


public class Fournisseurs {
		@FXML
		private Button submitButton;
		@FXML
		private TextField nom;
		@FXML
		private TextField prenom;
		@FXML
		private TextField adresse;
		@FXML
		private TextField email;
		@FXML
		private TextField tel;

	@FXML
	private TableColumn<?, ?> colAdresse;

	@FXML
	private TableColumn<?, ?> colEmail;

	@FXML
	private TableColumn<?, ?> colNom;

	@FXML
	private TableColumn<?, ?> colNum;

	@FXML
	private TableColumn<?, ?> colPrenom;

	@FXML
	private TableColumn<?, ?> colTel;
		public void getDataF(ActionEvent actionEvent) {
			System.out.println(nom.getText());
			System.out.println(prenom.getText());
			System.out.println(adresse.getText());
			System.out.println(email.getText());
			System.out.println(tel.getText());
			databaseConnection.writeToDatabase(nom.getText(), prenom.getText(), adresse.getText(),email.getText(), tel.getText());
		}
	public Connection getConnection() {
		Connection conn;
		try {
			conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/pharmacie","postgres","Salimiyati06");
			return conn;
		}
		catch (Exception e){
			e.printStackTrace();
			return null;
		}
	}
	public ObservableList<Fourni> getfourniList(){
		ObservableList<Fourni> fourniList = FXCollections.observableArrayList();
		Connection connection = getConnection();
		String query = "SELECT* FROM fournisseur ";
		Statement st;
		ResultSet rs;

		try {
			st = connection.createStatement();
			rs = st.executeQuery(query);
			Fourni fourni;
			while(rs.next()) {
				fourni = new Fourni(rs.getString("nom"),rs.getString("prenom"),rs.getString("adresse"),rs.getString("email"),rs.getInt("tel"));
				fourniList.add(fourni);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return fourniList;
	}
	}
