// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package PharmaGest;
import java.util.*;
/************************************************************/
/**
 * 
 */
public class Inventaire {
	/**
	 * 
	 */
	int num;
	/**
	 * 
	 */
	public Date date;
}
