// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package PharmaGest;

/************************************************************/
/**
 *
 */
public class Medicaments {
    /**
     *
     */
    public String DCI;
    /**
     *
     */
    String nom;
    /**
     *
     */
    public String dosage;
    /**
     *
     */
    public Stock stock;
}
