// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package PharmaGest;
import java.util.*;

/************************************************************/
/**
 * 
 */
class recu {
	/**
	 * 
	 */
	int num;
	/**
	 * 
	 */
	public Date[] date;
	/**
	 * 
	 */
	public Clients clients;
}
