// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package PharmaGest;
import java.util.*;

/************************************************************/
/**
 * 
 */
public class Stock {
	/**
	 * 
	 */
	public String code;
	/**
	 * 
	 */
	public Date dateFab;
	/**
	 * 
	 */
	public Date dateFin;
	/**
	 * 
	 */
	public Float prixUnit;
	/**
	 * 
	 */
	public Float prixGros;
	/**
	 * 
	 */
	public int quantStock;
	/**
	 * 
	 */
	public Utilisateurs utilisateurs;
}
