// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package PharmaGest;

/************************************************************/
/**
 * 
 */
public class Utilisateurs {
	/**
	 * 
	 */
	public String Pharmacien;
	/**
	 * 
	 */
	public Commande commande;
	/**
	 * 
	 */
	private String nom;
	/**
	 * 
	 */
	private String num;
	/**
	 * 
	 */
	private String prenom;
	/**
	 * 
	 */
	private String adresse;
	/**
	 * 
	 */
	private String tel;
	/**
	 * 
	 */
	private String email;
}
