// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package PharmaGest;
import java.util.*;
/************************************************************/
/**
 *
 */
public class Vente {
    /**
     *
     */
    public int num;
    /**
     *
     */
    public Date date;
    /**
     *
     */
    public Stock stock;
}
